export const t = new Map<string, string>([
    ["aeCost", "Kosten"],
    ["amount", "Anzahl"],
    ["cantrips", "Zaubertricks"],
    ["castingTime", "Zauberdauer"],
    ["combatTechnique", "Waffentechnik"],
    ["duration", "Wirkungsdauer"],
    ["effect", "Wirkung"],
    ["iniMod", "iniMod"],
    ["length", "Länge"],
    ["price", "Wert"],
    ["range", "Reichweite"],
    ["range", "Reichweite"],
    ["reach", "Reichweite"],
    ["reloadTime", "Nachladezeit"],
    ["weight", "Gewicht"],
])
